/* ============================================================
   WWII CAUSAL ATLAS — SHARED DATA MODEL
   Every event: id, date, year, theater, act, frame, title, caption, detail, icon
============================================================ */
const ACTS = [
  {n:1, title:'ORIGINS', years:'1919–1939',
    dek:'Two decades before the first shot of the Second World War, the terms of its opening act were already being written — in treaties, in bread lines, and in the speeches of men not yet in power.',
    eyebrow:'Before Frame One',
    intro:'This is not one story but the <strong>set-up for six</strong> — the economic collapse, the resentments, and the treaties broken one at a time that made a second world war possible. Nothing here is inevitable in hindsight; watch how each frame narrows the room for what comes next.'},
  {n:2, title:'BLITZKRIEG', years:'1939–1941',
    dek:'Negotiation gives way to invasion. In under a year Germany overruns most of continental Europe, while the Soviet Union — briefly its partner — watches its border creep west, until the partnership breaks entirely.',
    eyebrow:'Six Weeks, Six Countries',
    intro:'What began as a single invasion widens fast: neutral states fall in days, France — expected to hold — collapses in six weeks, and by the end of this reel Germany has turned east against the ally it signed a pact with barely two years earlier.'},
  {n:3, title:'THE WAR GOES GLOBAL', years:'1941–1942',
    dek:'A resource embargo half a world away from Europe\'s battlefields sets off a chain that turns two separate wars into one. Within days of a single morning attack, every major power on earth is at war.',
    eyebrow:'One Morning, Two Oceans',
    intro:'This is the shortest reel and the one with the widest consequences: a single attack pulls the United States into a war it had avoided, and alliance obligations do the rest — merging the war in Europe and the war in Asia into one global conflict.'},
  {n:4, title:'THE TURN', years:'1942–1943',
    dek:'On three continents at once, the Axis advance stalls, then reverses. No single battle ends the war here, but by the end of this reel, momentum has changed sides for good.',
    eyebrow:'The High-Water Mark',
    intro:'Watch the sequencing: within months of each other, Axis forces are stopped at El Alamein, at Stalingrad, and at Guadalcanal — three unrelated fronts reaching their limit at nearly the same time.'},
  {n:5, title:'COLLAPSE OF THE AXIS', years:'1944–1945',
    dek:'With the initiative gone, the Axis now fights a defensive war on every front simultaneously. Two Allied offensives, launched days apart on opposite sides of Europe, close the vice.',
    eyebrow:'Two Fronts, Closing',
    intro:'Notice the timing again: the landings in Normandy and the Soviet offensive in Belarus open just over two weeks apart — deliberately sequenced to prevent Germany from shifting forces between fronts.'},
  {n:6, title:'ENDGAME', years:'1945',
    dek:'The war\'s final months bring the costliest island battles of the Pacific, a conference that shapes the postwar world before the war is even over, and two weapons that end it in days.',
    eyebrow:'The Last Reel',
    intro:'This is where every thread — Europe, the Pacific, the diplomacy that started in Reel I — comes to a close within a single year, several endings arriving within days of each other.'},
];

const THEATERS = {
  origins: {label:'Origins & Diplomacy', hex:'#8A7CA8'},
  europe:  {label:'Western & Central Europe', hex:'#4C86A8'},
  eastern: {label:'Eastern Front', hex:'#B3453D'},
  pacific: {label:'Pacific', hex:'#3A8F7B'},
  china:   {label:'China', hex:'#8A9A4C'},
  africa:  {label:'North Africa & Mediterranean', hex:'#C9A227'},
};

const events = [
  // ---- REEL I — ORIGINS ----
  {id:'versailles', date:'June 1919', year:1919, theater:'origins', act:1, frame:'001', title:'The Treaty of Versailles',
   caption:'Germany signs the treaty ending the First World War, accepting reparations, territorial losses, and strict limits on its military.',
   detail:'Article 231 assigned responsibility for the war to Germany and its allies — a clause read in Germany as a demand to confess sole guilt. The treaty required substantial reparations payments, returned Alsace-Lorraine to France, and capped the German army at 100,000 men with no air force, tanks, or submarines. It was negotiated primarily by Britain, France, the United States, and Italy, with Germany excluded from the talks and presented the terms to sign.', icon:'seal'},
  {id:'depression', date:'1929', year:1929, theater:'origins', act:1, frame:'002', title:'The Great Depression',
   caption:'A global economic collapse, triggered by the Wall Street crash, brings mass unemployment and political instability across Europe.',
   detail:'By 1932, German unemployment approached 6 million — close to a third of the workforce. Banks failed across Central Europe, export economies collapsed, and mainstream parties lost credibility as they failed to reverse the slide. The crisis hit Germany, still repaying war reparations, with particular force.', icon:'crash'},
  {id:'manchuria', date:'September 1931', year:1931, theater:'china', act:1, frame:'003', title:'Japan Invades Manchuria',
   caption:'The Japanese Army occupies Manchuria in northeast China and establishes the puppet state of Manchukuo.',
   detail:'The invasion followed a staged explosion on a Japanese-controlled railway near Mukden, used as pretext. The League of Nations condemned the action; Japan responded by withdrawing from the League in 1933. It marked the first major territorial conquest by a future Axis power, eight years before war broke out in Europe.', icon:'flag'},
  {id:'hitler-power', date:'January 1933', year:1933, theater:'origins', act:1, frame:'004', title:'Hitler Appointed Chancellor',
   caption:'Adolf Hitler is appointed Chancellor of Germany, and within months moves to eliminate all political opposition.',
   detail:'Hitler was appointed by President Hindenburg as head of a coalition government. The Reichstag Fire in February 1933 was used to justify emergency powers, and the Enabling Act of March 1933 allowed Hitler to enact laws without parliamentary approval, effectively ending German democracy within two months.', icon:'podium'},
  {id:'rearmament', date:'1935–1936', year:1935, theater:'origins', act:1, frame:'005', title:'Rearmament & the Rhineland',
   caption:'Germany openly rebuilds its military and sends troops into the demilitarized Rhineland, breaking Versailles without consequence.',
   detail:'Conscription was reintroduced in 1935 and the Luftwaffe (air force) publicly unveiled — both forbidden under Versailles. In March 1936, German troops entered the Rhineland, a zone kept demilitarized by treaty. France and Britain, occupied with domestic concerns, did not intervene.', icon:'hammer'},
  {id:'sino-japanese', date:'July 1937', year:1937, theater:'china', act:1, frame:'006', title:'Full-Scale War in China',
   caption:'Fighting at the Marco Polo Bridge near Beijing escalates into a full-scale war between Japan and China.',
   detail:'What began as a skirmish between Japanese and Chinese troops expanded rapidly; by the end of 1937 Japan had captured Shanghai and Nanjing. The conflict would continue, largely independent of events in Europe, until it merged into the wider Pacific War in 1941.', icon:'arrows'},
  {id:'anschluss', date:'March 1938', year:1938, theater:'origins', act:1, frame:'007', title:'The Anschluss',
   caption:'Germany annexes Austria. No foreign power intervenes militarily.',
   detail:'German troops crossed into Austria on 12 March 1938, and a rigged plebiscite the following month recorded near-unanimous support for union with Germany. The annexation violated Versailles explicitly. Britain and France registered protest but took no action, reinforcing a pattern of unopposed expansion.', icon:'merge'},
  {id:'munich', date:'September 1938', year:1938, theater:'origins', act:1, frame:'008', title:'The Munich Agreement',
   caption:'Britain, France, Germany, and Italy sign an agreement allowing Germany to annex the Sudetenland region of Czechoslovakia.',
   detail:'Czechoslovakia itself was not party to the negotiations that decided its border. British Prime Minister Neville Chamberlain described the deal as securing "peace for our time." The Sudetenland contained Czechoslovakia\'s main border fortifications, which passed to Germany along with the territory.', icon:'document'},
  {id:'czech-occupy', date:'March 1939', year:1939, theater:'origins', act:1, frame:'009', title:'Czechoslovakia Dismantled',
   caption:'German troops occupy the remainder of Czechoslovakia, going beyond what Munich had granted.',
   detail:'This move broke the explicit terms of the Munich Agreement, which had only ceded the Sudetenland. Britain responded by extending a guarantee of military support to Poland, widely seen as likely next on the list — a commitment that would be tested within six months.', icon:'break'},
  {id:'molotov-ribbentrop', date:'August 1939', year:1939, theater:'origins', act:1, frame:'010', title:'The Molotov–Ribbentrop Pact',
   caption:'Germany and the Soviet Union sign a non-aggression pact, with a secret protocol dividing Eastern Europe into spheres of influence.',
   detail:'Signed by foreign ministers Vyacheslav Molotov and Joachim von Ribbentrop, the public pact bound both sides not to attack each other for ten years. A secret protocol, not disclosed until after the war, divided Poland, Finland, Estonia, Latvia, and Lithuania into German and Soviet zones. The pact freed Germany from the risk of a two-front war it had planned for.', icon:'signature'},

  // ---- REEL II — BLITZKRIEG ----
  {id:'poland-invasion', date:'1 Sep 1939', year:1939, theater:'europe', act:2, frame:'011', title:'Germany Invades Poland',
   caption:'German forces cross the Polish border, combining air power and armor in a fast-moving assault later termed "blitzkrieg."',
   detail:'German forces crossed the Polish border in the early hours of 1 September, using coordinated air and armored attacks. Contrary to a persistent claim, the Polish air force was not destroyed on the ground: it had dispersed to camouflaged reserve airfields before the invasion and kept flying for roughly two weeks. Organized Polish resistance continued for about five weeks, with the last major unit surrendering on 6 October.', icon:'tank'},
  {id:'declaration-war', date:'3 Sep 1939', year:1939, theater:'europe', act:2, frame:'012', title:'Britain and France Declare War',
   caption:'After an ultimatum to Germany expires unanswered, Britain and France declare war, formally beginning the European conflict.',
   detail:'Britain issued an ultimatum demanding German withdrawal from Poland; when it expired without response, Britain declared war, and France followed hours later. Neither country was in a position to offer Poland any immediate military relief.', icon:'megaphone'},
  {id:'ussr-poland', date:'17 Sep 1939', year:1939, theater:'europe', act:2, frame:'013', title:'The Soviet Union Enters Poland',
   caption:'Soviet troops cross into eastern Poland under the pact\'s secret protocol, opening a second front against the already-collapsing Polish state.',
   detail:'Soviet troops crossed into eastern Poland on 17 September, acting on the secret protocol of the Molotov–Ribbentrop Pact. Polish forces, already engaged against Germany in the west, faced a second front with little capacity to respond. Poland was partitioned between Germany and the USSR by early October.', icon:'merge'},
  {id:'winter-war', date:'Nov 1939', year:1939, theater:'eastern', act:2, frame:'014', title:'The Winter War', 
   caption:'The USSR attacks Finland after Finland rejects territorial demands; fierce Finnish resistance in brutal winter conditions inflicts heavy Soviet losses.',
   detail:'The USSR attacked Finland after Finland rejected Soviet demands for territorial concessions near Leningrad. Finnish forces mounted an unexpectedly effective defense in harsh winter conditions before a March 1940 peace treaty ceded roughly 10% of Finnish territory to the USSR.', icon:'break'},
  {id:'denmark-norway', date:'Apr 1940', year:1940, theater:'europe', act:2, frame:'015', title:'Denmark & Norway Occupied',
   caption:'Germany launches simultaneous operations against Denmark, which surrenders within hours, and Norway, which holds out for two months.',
   detail:'Germany launched simultaneous operations against Denmark, which surrendered within hours, and Norway, where fighting continued for about two months with British and French support before Norway fell. The campaign secured German access to Norwegian ports and Swedish iron-ore shipping routes.', icon:'tank'},
  {id:'low-countries', date:'May 1940', year:1940, theater:'europe', act:2, frame:'016', title:'The Low Countries Fall',
   caption:'Germany attacks the Netherlands, Belgium, and Luxembourg, bypassing France\'s fortified border by advancing through the Ardennes forest.',
   detail:'German forces attacked the Netherlands, Belgium, and Luxembourg on 10 May, bypassing France\'s fortified Maginot Line by advancing through the Ardennes forest, considered impassable to tanks. The Netherlands surrendered within five days; Belgium held out until 28 May.', icon:'tank'},
  {id:'france-fall', date:'Jun 1940', year:1940, theater:'europe', act:2, frame:'017', title:'France Surrenders',
   caption:'German armored divisions split Allied forces and reach the Channel; France signs an armistice within six weeks of the invasion beginning.',
   detail:'German armored divisions broke through French lines and reached the English Channel within two weeks, splitting Allied forces. France signed an armistice on 22 June; the northern two-thirds came under German occupation while a new French government, based in Vichy, administered the south.', icon:'handshake'},
  {id:'battle-britain', date:'Jul–Oct 1940', year:1940, theater:'europe', act:2, frame:'018', title:'The Battle of Britain',
   caption:'Germany\'s air force campaigns against British airfields and cities to prepare for invasion; Britain\'s defense holds, and the invasion is postponed.',
   detail:'Following France\'s fall, the German air force launched a sustained campaign against British airfields, infrastructure, and later cities, intended to establish the air superiority a cross-Channel invasion required. The Royal Air Force, aided by radar-directed defense, inflicted losses sufficient that Germany postponed its invasion plans indefinitely.', icon:'plane'},
  {id:'italy-africa', date:'Sep 1940', year:1940, theater:'africa', act:2, frame:'019', title:'Italy Opens the North African Front',
   caption:'Italian forces advance from Libya into British-held Egypt, aiming at the Suez Canal, before a British counteroffensive pushes them back.',
   detail:'Italian forces advanced from Libya into British-held Egypt in September 1940, aiming to threaten the Suez Canal. The advance stalled, and a British counteroffensive begun in December pushed Italian forces back deep into Libya, prompting Germany to send reinforcements the following year.', icon:'tank'},
  {id:'tripartite', date:'27 Sep 1940', year:1940, theater:'origins', act:2, frame:'020', title:'The Tripartite Pact',
   caption:'Germany, Italy, and Japan formalize a three-way military alliance, each committing to support the others if attacked by a new power.',
   detail:'Germany, Italy, and Japan formalized a mutual defense alliance, committing each to support the others if attacked by a power not already involved in the European or Sino-Japanese conflicts — a clause aimed chiefly at deterring the United States from entering either war.', icon:'alliance'},
  {id:'italy-greece', date:'28 Oct 1940', year:1940, theater:'africa', act:2, frame:'021', title:'Italy Invades Greece',
   caption:'Italy attacks Greece from Albania without coordinating with Germany; Greek forces halt the advance and push back into Albanian territory.',
   detail:'Italy launched an invasion of Greece from Italian-controlled Albania without prior coordination with Germany — Hitler learned of it only as it began. Greek forces halted the advance and pushed Italian troops back into Albanian territory, an unexpected setback that would draw German forces into the Balkans months later.', icon:'tank'},
  {id:'yugoslavia-greece', date:'Apr 1941', year:1941, theater:'africa', act:2, frame:'022', title:'Germany Occupies Yugoslavia & Greece',
   caption:'Germany invades both countries within weeks, rescuing Italy\'s stalled Greek campaign weeks before the invasion of the Soviet Union begins.',
   detail:'After a coup in Yugoslavia removed a government that had aligned with the Axis, and to rescue Italy\'s stalled campaign in Greece, Germany invaded both countries in April 1941. Both were occupied within weeks. Barbarossa then began about five weeks later than first scheduled — though how much of that delay the Balkans actually caused is disputed, with an unusually late spring thaw and unfinished logistics also cited.', icon:'tank'},
  {id:'barbarossa', date:'22 Jun 1941', year:1941, theater:'eastern', act:2, frame:'023', title:'Operation Barbarossa',
   caption:'Germany breaks its pact with the Soviet Union, launching the largest land invasion in history along a front from the Baltic to the Black Sea.',
   detail:'Germany launched the largest land invasion in history, deploying over three million troops. Initial advances were rapid, encircling large Soviet forces, but the campaign\'s timetable — intended to defeat the USSR before winter — was not met.', icon:'tank'},
  {id:'moscow-battle', date:'Oct 1941–Jan 1942', year:1941, theater:'eastern', act:2, frame:'024', title:'The Battle of Moscow',
   caption:'German forces reach the outskirts of the Soviet capital before being halted by resistance, exhaustion, and an unprepared-for winter.',
   detail:'German forces advanced to within sight of Moscow by early December before being halted by stiffening Soviet resistance, exhaustion, supply shortages, and severe winter weather for which German forces were not equipped. A Soviet counteroffensive pushed German lines back from the capital.', icon:'break'},

  // ---- REEL III — THE WAR GOES GLOBAL ----
  {id:'oil-embargo', date:'Aug 1941', year:1941, theater:'pacific', act:3, frame:'025', title:'The US Oil Embargo on Japan',
   caption:'After Japan occupies southern French Indochina, the US, Britain, and the Netherlands freeze Japanese assets and cut off oil exports.',
   detail:'After Japan occupied southern French Indochina, the United States, Britain, and the Netherlands froze Japanese assets and embargoed oil exports — a resource Japan depended on almost entirely from imports. Japanese planners viewed continued operations in China as unsustainable without securing alternative oil supplies, chiefly in Southeast Asia.', icon:'block'},
  {id:'pearl-harbor', date:'7 Dec 1941', year:1941, theater:'pacific', act:3, frame:'026', title:'Attack on Pearl Harbor',
   caption:'Japanese carrier aircraft strike the US Pacific Fleet at Hawaii, sinking or damaging eight battleships but missing the fleet\'s carriers, at sea.',
   detail:'Japanese carrier-based aircraft struck the US Pacific Fleet at anchor in Hawaii without a declaration of war reaching Washington before the attack began. The strike sank or damaged eight battleships and killed over 2,400 people, but missed the fleet\'s aircraft carriers, which were at sea.', icon:'plane'},
  {id:'us-enters', date:'8 Dec 1941', year:1941, theater:'pacific', act:3, frame:'027', title:'The United States Declares War',
   caption:'Congress approves a declaration of war against Japan the day after Pearl Harbor, ending prior American neutrality.',
   detail:'President Roosevelt asked Congress for a declaration of war the day after the attack, calling 7 December "a date which will live in infamy." The declaration passed with near-unanimous support, ending prior American neutrality in the conflict.', icon:'megaphone'},
  {id:'axis-declare-us', date:'11 Dec 1941', year:1941, theater:'origins', act:3, frame:'028', title:'Germany & Italy Declare War on the US',
   caption:'Honoring the Tripartite Pact, Germany and Italy declare war on the United States, merging the European and Pacific wars into one conflict.',
   detail:'Germany and Italy declared war on the United States four days after Pearl Harbor, honoring their Tripartite Pact obligations, though the pact\'s terms technically applied only to defensive situations. The declarations formally merged the European and Pacific conflicts into a single global war.', icon:'alliance'},
  {id:'japan-expansion', date:'Dec 1941–May 1942', year:1942, theater:'pacific', act:3, frame:'029', title:'Japan Sweeps Southeast Asia',
   caption:'Within six months of Pearl Harbor, Japan captures the Philippines, Malaya, Singapore, Hong Kong, Burma, and the Dutch East Indies.',
   detail:'Within six months of Pearl Harbor, Japan captured the Philippines, British Malaya and Singapore, Hong Kong, Burma, and the Dutch East Indies, securing the oil, rubber, and other resources the earlier embargo had denied it. The rapid conquest left Japan controlling a vast defensive perimeter across the Pacific and Southeast Asia.', icon:'flag'},

  // ---- REEL IV — THE TURN ----
  {id:'midway', date:'Jun 1942', year:1942, theater:'pacific', act:4, frame:'030', title:'The Battle of Midway',
   caption:'US codebreakers anticipate a Japanese attack on Midway; four Japanese fleet carriers are sunk, a loss Japan\'s naval air power never recovers from.',
   detail:'US codebreakers had partially decrypted Japanese naval communications, allowing the Pacific Fleet to anticipate a Japanese attack on Midway Atoll and position its carriers for an ambush. Four Japanese fleet carriers were sunk in exchange for one American carrier — a loss from which Japan\'s naval air power never fully recovered.', icon:'ship'},
  {id:'el-alamein', date:'Oct–Nov 1942', year:1942, theater:'africa', act:4, frame:'031', title:'The Battle of El Alamein',
   caption:'British Commonwealth forces halt a German-Italian advance toward Suez, then push Axis forces back across Libya.',
   detail:'British Commonwealth forces under General Montgomery halted a German-Italian advance toward the Suez Canal at El Alamein, then launched a counteroffensive that drove Axis forces back across Libya over the following months.', icon:'tank'},
  {id:'torch', date:'Nov 1942', year:1942, theater:'africa', act:4, frame:'032', title:'Operation Torch',
   caption:'American and British forces land in French North Africa, squeezing Axis forces between two advancing fronts.',
   detail:'American and British forces landed at multiple points along the coast of French North Africa, then under Vichy French control. After brief resistance, French forces there joined the Allies, combining with the British advance from Egypt to squeeze Axis forces from two directions.', icon:'wave'},
  {id:'stalingrad', date:'Aug 1942–Feb 1943', year:1942, theater:'eastern', act:4, frame:'033', title:'The Battle of Stalingrad',
   caption:'Months of street fighting end with the German Sixth Army encircled and forced to surrender — one of Germany\'s largest military losses of the war.',
   detail:'German forces fought street-by-street to capture the city, tying down the Sixth Army through the autumn of 1942. A Soviet counteroffensive in November encircled roughly 250,000 Axis troops; the remaining force surrendered in February 1943.', icon:'tank'},
  {id:'guadalcanal', date:'Aug 1942–Feb 1943', year:1942, theater:'pacific', act:4, frame:'034', title:'The Battle of Guadalcanal',
   caption:'Six months of fighting for a single airfield end in Japan\'s withdrawal — the first sustained Allied ground offensive against Japan.',
   detail:'US Marines landed on Guadalcanal to secure an airfield Japan was building there, beginning six months of intense ground, naval, and air fighting for the island. Japan\'s eventual withdrawal marked the first sustained Allied ground offensive of the Pacific war. (The first outright land defeat inflicted on Japanese forces had come weeks earlier at Milne Bay in New Guinea, where Australian troops repelled a landing in August–September 1942.)', icon:'island'},
  {id:'axis-africa-surrender', date:'May 1943', year:1943, theater:'africa', act:4, frame:'035', title:'Axis Forces Surrender in Africa',
   caption:'Squeezed between two advancing Allied armies, remaining German and Italian troops in Tunisia surrender, ending the African campaign.',
   detail:'Squeezed between British forces advancing from Egypt and Anglo-American forces from the west, the remaining German and Italian troops in Tunisia surrendered, ending Axis presence in Africa and yielding roughly 250,000 prisoners.', icon:'handshake'},
  {id:'sicily', date:'Jul 1943', year:1943, theater:'africa', act:4, frame:'036', title:'Allied Landings on Sicily',
   caption:'Allied forces secure Sicily within six weeks in the largest amphibious operation to that point; Mussolini\'s government collapses two weeks in.',
   detail:'Allied forces landed on Sicily on 9–10 July in the largest amphibious operation of the war to that point, securing the island within six weeks. The invasion brought down Mussolini within about two weeks: the Fascist Grand Council voted against him and the king dismissed and arrested him on 25 July.', icon:'wave'},
  {id:'kursk', date:'Jul 1943', year:1943, theater:'eastern', act:4, frame:'037', title:'The Battle of Kursk',
   caption:'Germany\'s massed tank offensive, anticipated by Soviet intelligence, ends in defeat — permanently handing the initiative to the USSR.',
   detail:'Germany attempted to eliminate a Soviet salient near Kursk with a massed armored offensive, anticipated by Soviet intelligence, which had prepared deep defensive lines. The battle, involving thousands of tanks, ended in a Soviet victory that permanently shifted the strategic initiative on the Eastern Front.', icon:'tank'},
  {id:'italy-surrender', date:'Sep 1943', year:1943, theater:'africa', act:4, frame:'038', title:'Italy Surrenders',
   caption:'The new Italian government secretly agrees an armistice with the Allies; Germany rapidly occupies the peninsula in response.',
   detail:'Following Mussolini\'s removal, the new Italian government secretly negotiated an armistice with the Allies. German forces, anticipating the move, rapidly occupied most of the Italian peninsula and continued fighting there alongside remaining fascist loyalists.', icon:'handshake'},
  {id:'island-hopping', date:'1943–44', year:1943, theater:'pacific', act:4, frame:'039', title:'"Island Hopping" Begins',
   caption:'Rather than assault every Japanese-held island, US forces selectively capture and bypass strongholds, isolating them from resupply.',
   detail:'Rather than assaulting every Japanese-held island, US forces selectively captured strategically useful islands and bypassed heavily fortified ones, isolating them from supply and reinforcement. The strategy allowed faster progress toward Japan while reducing casualties at bypassed strongpoints.', icon:'island'},

  // ---- REEL V — COLLAPSE OF THE AXIS ----
  {id:'dday', date:'6 Jun 1944', year:1944, theater:'europe', act:5, frame:'040', title:'D-Day: The Normandy Landings',
   caption:'Allied forces land on five Normandy beaches after a deception campaign convinces German commanders the main invasion would come at Calais.',
   detail:'Allied forces landed on five beach sectors along the Normandy coast, supported by airborne landings and a deception campaign that had convinced German commanders the main invasion would come further north at Calais. Establishing a secure beachhead opened a sustained second front in Western Europe.', icon:'wave'},
  {id:'bagration', date:'Jun 1944', year:1944, theater:'eastern', act:5, frame:'041', title:'Operation Bagration',
   caption:'Timed with the Normandy landings, a massive Soviet offensive destroys much of Germany\'s Army Group Center in Belarus.',
   detail:'Timed to coincide with the Normandy landings, the Soviet offensive in Belarus destroyed a substantial portion of Germany\'s Army Group Center, inflicting losses comparable to or exceeding those at Stalingrad and driving German forces back toward Poland.', icon:'tank'},
  {id:'paris-liberated', date:'Aug 1944', year:1944, theater:'europe', act:5, frame:'042', title:'Paris Is Liberated',
   caption:'A resistance uprising coincides with the arrival of Allied troops; the German garrison surrenders rather than destroy the city as ordered.',
   detail:'As Allied forces advanced from Normandy, a French resistance uprising in Paris coincided with the arrival of Free French and American troops, and the German commander surrendered the city rather than carry out Hitler\'s demolition order — though how much destructive capacity the garrison still had is debated.', icon:'flag'},
  {id:'leyte-gulf', date:'Oct 1944', year:1944, theater:'pacific', act:5, frame:'043', title:'The Battle of Leyte Gulf',
   caption:'The largest naval battle of the war leaves Japan\'s navy unable to mount another major operation, and sees the first organized kamikaze attacks.',
   detail:'In the largest naval battle of the war, Japan committed nearly its entire remaining fleet in an attempt to destroy American forces supporting the invasion of the Philippines. The battle included the first organized kamikaze attacks and left the Japanese navy unable to mount another major operation for the rest of the war.', icon:'ship'},
  {id:'bulge', date:'Dec 1944–Jan 1945', year:1944, theater:'europe', act:5, frame:'044', title:'The Battle of the Bulge',
   caption:'Germany\'s last major offensive in the west aims to split Allied lines; stiffening resistance and clearing weather wear it down within six weeks.',
   detail:'Germany massed forces for a surprise offensive through the Ardennes forest, aiming to split Allied lines and recapture the port of Antwerp. Initial gains created a visible bulge in Allied lines, but stiffening resistance, reinforcements, and clearing weather that allowed Allied air support wore the offensive down within six weeks.', icon:'tank'},

  // ---- REEL VI — ENDGAME ----
  {id:'yalta', date:'Feb 1945', year:1945, theater:'origins', act:6, frame:'045', title:'The Yalta Conference',
   caption:'Roosevelt, Churchill, and Stalin meet to plan postwar Germany, Poland\'s borders, and Soviet entry into the war against Japan.',
   detail:'With German defeat increasingly certain, Roosevelt, Churchill, and Stalin met in Crimea to discuss the postwar division of Germany, the borders of Poland, the structure of the United Nations, and Soviet entry into the war against Japan within three months of Germany\'s surrender.', icon:'table'},
  {id:'iwo-jima', date:'Feb–Mar 1945', year:1945, theater:'pacific', act:6, frame:'046', title:'The Battle of Iwo Jima',
   caption:'US Marines take the fortified island, valued for its airfields, against a Japanese garrison dug into an extensive tunnel network.',
   detail:'US Marines landed on the small volcanic island, valued for its airfields within fighter range of Japan, against a Japanese garrison dug into an extensive tunnel network. Nearly the entire Japanese garrison was killed, and American casualties were also severe relative to the island\'s size.', icon:'wave'},
  {id:'okinawa', date:'Apr–Jun 1945', year:1945, theater:'pacific', act:6, frame:'047', title:'The Battle of Okinawa',
   caption:'The largest US amphibious campaign of the Pacific war sees sustained kamikaze attacks and heavy losses on all sides over nearly three months.',
   detail:'The invasion of Okinawa, intended as a staging area for an eventual invasion of the Japanese home islands, saw sustained kamikaze attacks on the invasion fleet and heavy casualties among Japanese and Allied combatants and Okinawan civilians alike — casualties that informed later estimates of the cost of invading Japan directly.', icon:'wave'},
  {id:'berlin-fall', date:'Apr–May 1945', year:1945, theater:'eastern', act:6, frame:'048', title:'The Fall of Berlin',
   caption:'Soviet forces encircle and fight through Berlin block by block; Hitler takes his own life as the city\'s garrison surrenders days later.',
   detail:'Soviet forces encircled Berlin in late April 1945, fighting through the city block by block. With Soviet troops within blocks of his bunker and no prospect of relief, Hitler took his own life on 30 April; the city\'s garrison surrendered days later.', icon:'break'},
  {id:'ve-day', date:'7–8 May 1945', year:1945, theater:'europe', act:6, frame:'049', title:'VE Day — Germany Surrenders',
   caption:'German commanders sign instruments of unconditional surrender, formally ending the war in Europe while the Pacific war continues.',
   detail:'Following Hitler\'s death and the fall of Berlin, German commanders signed instruments of unconditional surrender, formally ending the war in Europe. Celebrations broke out across Allied nations, though the war against Japan continued.', icon:'handshake'},
  {id:'hiroshima', date:'6 Aug 1945', year:1945, theater:'pacific', act:6, frame:'050', title:'The Atomic Bombing of Hiroshima',
   caption:'The United States drops the first atomic weapon used in warfare on Hiroshima, destroying most of the city.',
   detail:'The United States dropped an atomic bomb on Hiroshima, a city of roughly 350,000, destroying most of the city and killing an estimated 70,000–140,000 people by the end of the year from the blast and its aftermath. It was the first use of a nuclear weapon in warfare.', icon:'explosion'},
  {id:'ussr-japan', date:'8 Aug 1945', year:1945, theater:'pacific', act:6, frame:'051', title:'The Soviet Union Declares War on Japan',
   caption:'Honoring its Yalta commitment, the USSR invades Japanese-occupied Manchuria, removing any prospect of a Moscow-mediated peace.',
   detail:'Honoring its Yalta commitment, the Soviet Union declared war on Japan and launched a large offensive into Japanese-occupied Manchuria, rapidly overwhelming Japanese forces there and removing any prospect of a negotiated peace mediated through Moscow, which some Japanese officials had been pursuing.', icon:'flag'},
  {id:'nagasaki', date:'9 Aug 1945', year:1945, theater:'pacific', act:6, frame:'052', title:'The Atomic Bombing of Nagasaki',
   caption:'Three days after Hiroshima, a second atomic bomb is dropped on Nagasaki as Japanese leadership deliberates over surrender.',
   detail:'Three days after Hiroshima, the United States dropped a second atomic bomb on Nagasaki, killing an estimated 40,000–80,000 people by the end of the year. Japanese leadership, already weighing surrender, deliberated over the following days.', icon:'explosion'},
  {id:'japan-surrender', date:'15 Aug 1945', year:1945, theater:'pacific', act:6, frame:'053', title:'Japan Announces Surrender',
   caption:'Emperor Hirohito announces Japan\'s acceptance of surrender terms in a radio broadcast — the first time most citizens had heard his voice.',
   detail:'Emperor Hirohito announced Japan\'s acceptance of Allied surrender terms in a radio broadcast to the Japanese public, the first time most citizens had heard his voice. Fighting largely ceased, though the formal surrender document remained to be signed.', icon:'megaphone'},
  {id:'vj-day', date:'2 Sep 1945', year:1945, theater:'pacific', act:6, frame:'054', title:'Formal Japanese Surrender',
   caption:'Japanese representatives sign the Instrument of Surrender aboard the USS Missouri in Tokyo Bay, formally ending the Second World War.',
   detail:'Japanese representatives signed the Instrument of Surrender aboard the USS Missouri in Tokyo Bay, formally ending the Second World War — a conflict that, by most estimates, killed between 70 and 85 million people worldwide.', icon:'document'},
];

// causal links: {source, target, label} — short & neutral (mechanism, not judgment)
const links = [
  {source:'versailles', target:'hitler-power', label:'precondition'},
  {source:'versailles', target:'rearmament', label:'terms later broken'},
  {source:'depression', target:'hitler-power', label:'economic shock → political shift'},
  {source:'hitler-power', target:'rearmament', label:'new policy direction'},
  {source:'rearmament', target:'anschluss', label:'military capacity'},
  {source:'manchuria', target:'sino-japanese', label:'conflict expands'},
  {source:'anschluss', target:'munich', label:'precedent for annexation'},
  {source:'munich', target:'czech-occupy', label:'agreement exceeded'},
  {source:'czech-occupy', target:'molotov-ribbentrop', label:'shifted diplomatic map'},
  {source:'molotov-ribbentrop', target:'poland-invasion', label:'eastern flank secured'},
  {source:'poland-invasion', target:'declaration-war', label:'direct response'},
  {source:'molotov-ribbentrop', target:'ussr-poland', label:'secret protocol'},
  {source:'molotov-ribbentrop', target:'winter-war', label:'Soviet sphere of influence'},
  {source:'declaration-war', target:'denmark-norway', label:'war escalates'},
  {source:'denmark-norway', target:'low-countries', label:'campaign continues'},
  {source:'low-countries', target:'france-fall', label:'advance continues'},
  {source:'france-fall', target:'battle-britain', label:'focus shifts to Britain'},
  {source:'tripartite', target:'italy-greece', label:'Axis coordination'},
  {source:'italy-africa', target:'italy-greece', label:'Italian front widens'},
  {source:'italy-greece', target:'yugoslavia-greece', label:'German support intervention'},
  {source:'molotov-ribbentrop', target:'barbarossa', label:'pact broken'},
  {source:'battle-britain', target:'barbarossa', label:'strategic pivot east'},
  {source:'barbarossa', target:'moscow-battle', label:'advance on the capital'},
  {source:'sino-japanese', target:'oil-embargo', label:'international response'},
  {source:'tripartite', target:'oil-embargo', label:'expansion concerns'},
  {source:'oil-embargo', target:'pearl-harbor', label:'resource pressure'},
  {source:'pearl-harbor', target:'us-enters', label:'direct response'},
  {source:'tripartite', target:'axis-declare-us', label:'alliance commitment'},
  {source:'us-enters', target:'axis-declare-us', label:'alliance escalation'},
  {source:'pearl-harbor', target:'japan-expansion', label:'simultaneous offensives'},
  {source:'oil-embargo', target:'japan-expansion', label:'seeking alternate resources'},
  {source:'japan-expansion', target:'midway', label:'US counteroffensive'},
  {source:'midway', target:'guadalcanal', label:'initiative shifts'},
  {source:'italy-africa', target:'el-alamein', label:'prolonged fighting'},
  {source:'el-alamein', target:'torch', label:'coordinated pincer'},
  {source:'moscow-battle', target:'stalingrad', label:'offensive continues south'},
  {source:'torch', target:'axis-africa-surrender', label:'Allied pincer'},
  {source:'el-alamein', target:'axis-africa-surrender', label:'Allied pincer'},
  {source:'axis-africa-surrender', target:'sicily', label:'focus shifts to Italy'},
  {source:'stalingrad', target:'kursk', label:'Soviet position consolidates'},
  {source:'sicily', target:'italy-surrender', label:'military & political pressure'},
  {source:'guadalcanal', target:'island-hopping', label:'strategy continuation'},
  {source:'kursk', target:'bagration', label:'USSR holds initiative'},
  {source:'sicily', target:'dday', label:'amphibious landing experience'},
  {source:'dday', target:'paris-liberated', label:'advance from the coast'},
  {source:'bagration', target:'berlin-fall', label:'advance westward'},
  {source:'island-hopping', target:'leyte-gulf', label:'approach to Philippines'},
  {source:'dday', target:'bulge', label:'German counteroffensive on this front'},
  {source:'bagration', target:'yalta', label:'shapes postwar planning'},
  {source:'bulge', target:'ve-day', label:'German forces weakened'},
  {source:'berlin-fall', target:'ve-day', label:'command center collapses'},
  {source:'island-hopping', target:'iwo-jima', label:'approach to Japan'},
  {source:'iwo-jima', target:'okinawa', label:'advance continues'},
  {source:'yalta', target:'ussr-japan', label:'commitment to enter war'},
  {source:'okinawa', target:'hiroshima', label:'invasion cost estimates'},
  {source:'hiroshima', target:'ussr-japan', label:'near-simultaneous events'},
  {source:'ussr-japan', target:'nagasaki', label:'near-simultaneous events'},
  {source:'hiroshima', target:'nagasaki', label:'follows directly'},
  {source:'nagasaki', target:'japan-surrender', label:'surrender decision'},
  {source:'ussr-japan', target:'japan-surrender', label:'loss of ability to continue'},
  {source:'japan-surrender', target:'vj-day', label:'formal signing'},
];

// connector pills shown between consecutive Watch-mode events within an act (only where a direct link exists)
const connectors = {
  'hitler-power->rearmament': 'new leadership, new policy',
  'anschluss->munich': 'precedent for further annexation',
  'munich->czech-occupy': 'agreement exceeded within months',
  'czech-occupy->molotov-ribbentrop': 'shifted the diplomatic map',
  'poland-invasion->declaration-war': 'direct response',
  'declaration-war->ussr-poland': null,
  'denmark-norway->low-countries': 'campaign continues',
  'low-countries->france-fall': 'advance continues',
  'france-fall->battle-britain': 'focus shifts to Britain',
  'italy-africa->tripartite': null,
  'tripartite->italy-greece': 'Axis coordination',
  'italy-greece->yugoslavia-greece': 'German support intervention',
  'yugoslavia-greece->barbarossa': null,
  'barbarossa->moscow-battle': 'advance on the capital',
  'oil-embargo->pearl-harbor': 'resource pressure',
  'pearl-harbor->us-enters': 'direct response',
  'us-enters->axis-declare-us': 'alliance escalation',
  'axis-declare-us->japan-expansion': null,
  'el-alamein->torch': 'coordinated pincer',
  'torch->stalingrad': null,
  'stalingrad->guadalcanal': null,
  'axis-africa-surrender->sicily': 'focus shifts to Italy',
  'sicily->kursk': null,
  'kursk->italy-surrender': null,
  'italy-surrender->island-hopping': null,
  'bagration->paris-liberated': null,
  'paris-liberated->leyte-gulf': null,
  'leyte-gulf->bulge': null,
  'iwo-jima->okinawa': 'advance continues',
  'okinawa->berlin-fall': null,
  'berlin-fall->ve-day': 'command center collapses',
  've-day->hiroshima': null,
  'hiroshima->ussr-japan': 'near-simultaneous events',
  'ussr-japan->nagasaki': 'near-simultaneous events',
  'nagasaki->japan-surrender': 'surrender decision',
  'japan-surrender->vj-day': 'formal signing',
};

/* minimal amber line-icons */
const icons = {
  seal: `<svg viewBox="0 0 100 100"><circle class="stroke" cx="50" cy="42" r="26"/><path class="stroke" d="M38 42l8 8 16-16"/><path class="stroke" d="M34 64 L28 92 L50 80 L72 92 L66 64"/></svg>`,
  crash: `<svg viewBox="0 0 100 100"><path class="stroke" d="M10 30h80M10 30v55h80"/><path class="stroke" d="M18 55 L38 40 L52 52 L90 20"/><circle class="fill" cx="90" cy="20" r="3"/></svg>`,
  flag: `<svg viewBox="0 0 100 100"><path class="stroke" d="M28 10v82"/><path class="stroke fill" d="M28 14 L78 26 L28 40 Z"/><ellipse class="stroke dim" cx="50" cy="88" rx="34" ry="6"/></svg>`,
  podium: `<svg viewBox="0 0 100 100"><path class="stroke" d="M30 90 L38 40 L62 40 L70 90"/><rect class="stroke" x="24" y="90" width="52" height="4"/><circle class="fill" cx="50" cy="22" r="10"/><path class="stroke" d="M38 40 Q50 30 62 40"/></svg>`,
  hammer: `<svg viewBox="0 0 100 100"><rect class="stroke fill" x="52" y="14" width="34" height="20" rx="2" transform="rotate(45 69 24)"/><path class="stroke" d="M52 34 L22 64"/><path class="stroke" d="M14 72 L22 64 L30 72 L22 84 Z"/></svg>`,
  arrows: `<svg viewBox="0 0 100 100"><path class="stroke" d="M15 35h50"/><path class="stroke" d="M55 25 L67 35 L55 45"/><path class="stroke" d="M85 65H35"/><path class="stroke" d="M45 55 L33 65 L45 75"/></svg>`,
  merge: `<svg viewBox="0 0 100 100"><path class="stroke" d="M20 20 L50 50"/><path class="stroke" d="M80 20 L50 50"/><path class="stroke" d="M50 50 L50 90"/><circle class="fill" cx="50" cy="50" r="4"/></svg>`,
  document: `<svg viewBox="0 0 100 100"><rect class="stroke" x="26" y="12" width="48" height="64" rx="2"/><path class="stroke dim" d="M36 30h28M36 42h28M36 54h18"/><path class="stroke" d="M30 88 L50 76 L70 88"/></svg>`,
  break: `<svg viewBox="0 0 100 100"><path class="stroke" d="M10 50 L38 50 L46 30 L54 70 L62 50 L90 50"/></svg>`,
  signature: `<svg viewBox="0 0 100 100"><path class="stroke" d="M15 70 Q30 30 40 60 Q50 90 60 40 Q68 15 75 55 Q80 75 90 60"/><path class="stroke dim" d="M15 82h70"/></svg>`,
  spark: `<svg viewBox="0 0 100 100"><path class="stroke" d="M50 12 L58 42 L88 50 L58 58 L50 88 L42 58 L12 50 L42 42 Z"/></svg>`,
  tank: `<svg viewBox="0 0 100 100"><rect class="stroke" x="20" y="50" width="60" height="20" rx="4"/><rect class="stroke" x="35" y="38" width="26" height="14" rx="2"/><path class="stroke" d="M61 44h28"/><ellipse class="stroke dim" cx="32" cy="74" rx="10" ry="6"/><ellipse class="stroke dim" cx="68" cy="74" rx="10" ry="6"/></svg>`,
  plane: `<svg viewBox="0 0 100 100"><path class="stroke" d="M50 10 L50 70"/><path class="stroke" d="M15 45 L85 45"/><path class="stroke" d="M40 70 L50 90 L60 70"/><path class="fill" d="M50 10 L58 30 L42 30 Z"/></svg>`,
  handshake: `<svg viewBox="0 0 100 100"><path class="stroke" d="M10 50 Q30 35 45 50 L55 50 Q70 35 90 50"/><path class="stroke" d="M45 50 L38 58 M55 50 L62 58"/><path class="stroke dim" d="M20 62 L35 50 M80 62 L65 50"/></svg>`,
  alliance: `<svg viewBox="0 0 100 100"><circle class="stroke" cx="38" cy="40" r="22"/><circle class="stroke" cx="62" cy="40" r="22"/><circle class="stroke" cx="50" cy="64" r="22"/></svg>`,
  megaphone: `<svg viewBox="0 0 100 100"><path class="stroke fill" d="M20 45 L55 25 L55 75 L20 55 Z"/><path class="stroke" d="M55 30 Q80 40 80 50 Q80 60 55 70"/><path class="stroke dim" d="M20 55 L14 70"/></svg>`,
  block: `<svg viewBox="0 0 100 100"><circle class="stroke" cx="50" cy="50" r="32"/><path class="stroke" d="M27 27 L73 73"/></svg>`,
  ship: `<svg viewBox="0 0 100 100"><path class="stroke" d="M15 62 L85 62 L72 82 L28 82 Z"/><path class="stroke" d="M50 62 L50 18"/><path class="stroke fill" d="M50 20 L74 40 L50 40 Z"/></svg>`,
  wave: `<svg viewBox="0 0 100 100"><path class="stroke" d="M10 55 Q22 45 34 55 T58 55 T82 55"/><path class="stroke" d="M10 70 Q22 60 34 70 T58 70 T82 70"/><path class="stroke" d="M50 40 L50 15"/><path class="stroke fill" d="M42 22 L50 10 L58 22 Z"/></svg>`,
  island: `<svg viewBox="0 0 100 100"><path class="stroke" d="M10 65 Q25 55 40 65 T70 65 T95 65"/><circle class="fill" cx="50" cy="45" r="10"/><path class="stroke dim" d="M50 35 L50 20"/></svg>`,
  table: `<svg viewBox="0 0 100 100"><ellipse class="stroke" cx="50" cy="55" rx="34" ry="16"/><circle class="fill" cx="50" cy="30" r="5"/><circle class="fill" cx="26" cy="42" r="5"/><circle class="fill" cx="74" cy="42" r="5"/></svg>`,
  explosion: `<svg viewBox="0 0 100 100"><path class="stroke" d="M50 90 L50 55"/><ellipse class="stroke fill" cx="50" cy="35" rx="28" ry="22"/><path class="stroke dim" d="M35 55 Q50 65 65 55"/></svg>`,
};
